import Head from 'next/head'
import WelcomeStep from 'components/InitialSteps/WelcomeStep'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Clubhouse Clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <WelcomeStep />
      </main>
    </div>
  )
}
